name: finar

services:
  postgres:
    container_name: finar-postgres
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${FINAR_POSTGRES_PASSWORD}
      - POSTGRES_USER=app
      - POSTGRES_DB=finar
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql
  redis:
    container_name: finar-redis
    image: redis
  nginx:
    container_name: finar-nginx
    build:
      context: nginx
    ports:
      - 8889:80
    depends_on:
      - backend
      - frontend
  backend:
    container_name: finar-backend
    build:
      context: backend
    environment:
      - REDIS_HOST=finar-redis
      - POSTGRES_HOST=finar-postgres
      - POSTGRES_USERNAME=app
      - POSTGRES_PASSWORD=${FINAR_POSTGRES_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
  frontend:
    container_name: finar-frontend
    build:
      context: client
volumes:
  pgdata:
