spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: src/main/resources/schema.sql
logging:
  level:
    root: WARN
    org.springframework:
      web: DEBUG
      security: DEBUG
    com.skyegibney.finar:
      game: DEBUG
      notifications: DEBUG
      matchmaking: DEBUG
      websockets: DEBUG
      authorization: DEBUG
server:
  port: 8000

logging.level.com.skyegibney.finar.game: DEBUG
logging.level.com.skyegibney.finar.notifications: DEBUG
