spring:
  application:
    name: finar
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}/finar?user=${POSTGRES_USERNAME}&password=${POSTGRES_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
server:
  servlet:
    session:
      timeout: 60s