spring:
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
logging:
  level:
    root: WARN
    org.springframework:
      web: DEBUG
      security: DEBUG
    com.skyegibney.finar:
      game: DEBUG
      notifications: DEBUG
      matchmaking: DEBUG
      websockets: DEBUG
      authorization: DEBUG

logging.level.com.skyegibney.finar.game: DEBUG
logging.level.com.skyegibney.finar.notifications: DEBUG
