spring:
  application:
    name: finar
  datasource:
    url: jdbc:postgresql://${PG_HOST}/finar?user=${PG_USERNAME}&password=${PG_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
server:
  servlet:
    session:
      timeout: 60s
  port: 8000